import { Meetup, MeetupCategory } from '../types';

export function getMockMeetups(): Meetup[] {
  const now = new Date();
  const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
  const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

  return [
    {
      id: '1',
      businessId: 'biz1',
      businessName: 'Café Central Munich',
      businessLogo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=100',
      businessIsPartner: true,
      category: 'COFFEE' as MeetupCategory,
      title: '☕ Morning Coffee & Networking',
      description: 'Start your day with great coffee and conversation. Perfect for freelancers, entrepreneurs, and creatives looking to connect.',
      startTime: new Date(tomorrow.setHours(9, 0)).toISOString(),
      endTime: new Date(tomorrow.setHours(10, 30)).toISOString(),
      capacity: 4,
      participants: [
        {
          userId: 'user1',
          userName: 'Sarah M.',
          userAvatar: 'https://i.pravatar.cc/150?img=1',
          userLevel: 5,
          joinedAt: new Date().toISOString(),
          checkedIn: false,
          missionsCompleted: []
        },
        {
          userId: 'user2',
          userName: 'Tom K.',
          userAvatar: 'https://i.pravatar.cc/150?img=12',
          userLevel: 3,
          joinedAt: new Date().toISOString(),
          checkedIn: false,
          missionsCompleted: []
        }
      ],
      location: {
        latitude: 48.1351,
        longitude: 11.5820,
        address: 'Marienplatz 8',
        city: 'Munich',
        district: 'Altstadt'
      },
      levelRequired: 1,
      rewardId: 'reward1',
      rewardTitle: 'Free Croissant',
      rewardType: 'FREE_ITEM',
      rewardValue: 1,
      missions: ['mission1', 'mission2'],
      xpReward: 100,
      stamp: 'Coffee Explorer',
      status: 'upcoming',
      aiGenerated: true,
      partnerPriority: 85,
      weatherRelevance: 'indoor',
      timeOfDay: 'morning',
      vibeMatch: ['professional', 'creative', 'social'],
      distanceLimit: 2000,
      chatId: 'chat1',
      viewCount: 45,
      joinRequestCount: 12,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: '2',
      businessId: 'biz2',
      businessName: 'FitZone Gym',
      businessLogo: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=100',
      businessIsPartner: true,
      category: 'FITNESS' as MeetupCategory,
      title: '💪 Evening Workout Squad',
      description: 'Join a group workout session followed by protein shakes. All fitness levels welcome!',
      startTime: new Date(tomorrow.setHours(18, 0)).toISOString(),
      endTime: new Date(tomorrow.setHours(19, 30)).toISOString(),
      capacity: 4,
      participants: [
        {
          userId: 'user3',
          userName: 'Lisa P.',
          userAvatar: 'https://i.pravatar.cc/150?img=5',
          userLevel: 7,
          joinedAt: new Date().toISOString(),
          checkedIn: false,
          missionsCompleted: []
        }
      ],
      location: {
        latitude: 48.1461,
        longitude: 11.5687,
        address: 'Leopoldstraße 45',
        city: 'Munich',
        district: 'Schwabing'
      },
      levelRequired: 2,
      rewardId: 'reward2',
      rewardTitle: '50% Off Protein Shake',
      rewardType: 'DISCOUNT',
      rewardValue: 50,
      missions: ['mission3'],
      xpReward: 150,
      stamp: 'Fitness Enthusiast',
      status: 'upcoming',
      aiGenerated: false,
      partnerPriority: 90,
      weatherRelevance: 'indoor',
      timeOfDay: 'evening',
      vibeMatch: ['active', 'health-conscious', 'motivated'],
      distanceLimit: 3000,
      viewCount: 67,
      joinRequestCount: 23,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: '3',
      businessId: 'biz3',
      businessName: 'Trattoria Italiana',
      businessLogo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=100',
      businessIsPartner: true,
      category: 'DINNER' as MeetupCategory,
      title: '🍝 Italian Dinner Experience',
      description: 'Enjoy authentic Italian cuisine with fellow food lovers. Wine pairing included!',
      startTime: new Date(nextWeek.setHours(19, 30)).toISOString(),
      endTime: new Date(nextWeek.setHours(21, 30)).toISOString(),
      capacity: 4,
      participants: [],
      location: {
        latitude: 48.1391,
        longitude: 11.5751,
        address: 'Maximilianstraße 12',
        city: 'Munich',
        district: 'Maxvorstadt'
      },
      levelRequired: 3,
      rewardId: 'reward3',
      rewardTitle: 'Complimentary Dessert',
      rewardType: 'FREE_ITEM',
      rewardValue: 1,
      missions: ['mission4', 'mission5'],
      xpReward: 200,
      stamp: 'Dinner Socializer',
      status: 'upcoming',
      aiGenerated: true,
      partnerPriority: 95,
      weatherRelevance: 'any',
      timeOfDay: 'evening',
      vibeMatch: ['foodie', 'social', 'sophisticated'],
      distanceLimit: 5000,
      viewCount: 89,
      joinRequestCount: 34,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: '4',
      businessId: 'biz4',
      businessName: 'Creative Hub',
      businessLogo: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=100',
      businessIsPartner: false,
      category: 'CREATIVE' as MeetupCategory,
      title: '🎨 Art & Design Workshop',
      description: 'Hands-on creative session for designers, artists, and curious minds.',
      startTime: new Date(tomorrow.setHours(14, 0)).toISOString(),
      endTime: new Date(tomorrow.setHours(16, 0)).toISOString(),
      capacity: 4,
      participants: [
        {
          userId: 'user4',
          userName: 'Max B.',
          userAvatar: 'https://i.pravatar.cc/150?img=8',
          userLevel: 4,
          joinedAt: new Date().toISOString(),
          checkedIn: false,
          missionsCompleted: []
        },
        {
          userId: 'user5',
          userName: 'Emma S.',
          userAvatar: 'https://i.pravatar.cc/150?img=9',
          userLevel: 6,
          joinedAt: new Date().toISOString(),
          checkedIn: false,
          missionsCompleted: []
        },
        {
          userId: 'user6',
          userName: 'Oliver W.',
          userAvatar: 'https://i.pravatar.cc/150?img=13',
          userLevel: 5,
          joinedAt: new Date().toISOString(),
          checkedIn: false,
          missionsCompleted: []
        }
      ],
      location: {
        latitude: 48.1500,
        longitude: 11.5900,
        address: 'Sendlinger Straße 33',
        city: 'Munich',
        district: 'Sendling'
      },
      levelRequired: 2,
      missions: [],
      xpReward: 0, // Non-partner = no XP
      status: 'upcoming',
      aiGenerated: false,
      partnerPriority: 20,
      weatherRelevance: 'indoor',
      timeOfDay: 'afternoon',
      vibeMatch: ['creative', 'artistic', 'curious'],
      distanceLimit: 4000,
      viewCount: 52,
      joinRequestCount: 18,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: '5',
      businessId: 'biz5',
      businessName: 'Zen Yoga Studio',
      businessLogo: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=100',
      businessIsPartner: true,
      category: 'WELLNESS' as MeetupCategory,
      title: '🧘 Sunrise Yoga & Meditation',
      description: 'Start your weekend with mindfulness. Beginners welcome, mats provided.',
      startTime: new Date(nextWeek.setHours(7, 0)).toISOString(),
      endTime: new Date(nextWeek.setHours(8, 30)).toISOString(),
      capacity: 4,
      participants: [],
      location: {
        latitude: 48.1281,
        longitude: 11.5606,
        address: 'Goethestraße 55',
        city: 'Munich',
        district: 'Haidhausen'
      },
      levelRequired: 1,
      rewardId: 'reward5',
      rewardTitle: '20% Off Monthly Pass',
      rewardType: 'DISCOUNT',
      rewardValue: 20,
      missions: ['mission6'],
      xpReward: 120,
      stamp: 'Wellness Warrior',
      status: 'upcoming',
      aiGenerated: true,
      partnerPriority: 80,
      weatherRelevance: 'indoor',
      timeOfDay: 'morning',
      vibeMatch: ['mindful', 'wellness', 'peaceful'],
      distanceLimit: 3000,
      viewCount: 38,
      joinRequestCount: 15,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: '6',
      businessId: 'biz6',
      businessName: 'Business Lounge',
      businessLogo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=100',
      businessIsPartner: true,
      category: 'BUSINESS' as MeetupCategory,
      title: '💼 Entrepreneur Networking',
      description: 'Connect with fellow entrepreneurs, share experiences, and build meaningful business relationships.',
      startTime: new Date(tomorrow.setHours(17, 0)).toISOString(),
      endTime: new Date(tomorrow.setHours(18, 30)).toISOString(),
      capacity: 4,
      participants: [
        {
          userId: 'user7',
          userName: 'Anna L.',
          userAvatar: 'https://i.pravatar.cc/150?img=10',
          userLevel: 8,
          joinedAt: new Date().toISOString(),
          checkedIn: false,
          missionsCompleted: []
        }
      ],
      location: {
        latitude: 48.1420,
        longitude: 11.5780,
        address: 'Ludwigstraße 8',
        city: 'Munich',
        district: 'Maxvorstadt'
      },
      levelRequired: 5,
      rewardId: 'reward6',
      rewardTitle: 'Free Coffee & Snacks',
      rewardType: 'FREE_ITEM',
      rewardValue: 1,
      missions: ['mission7'],
      xpReward: 180,
      stamp: 'Business Networker',
      status: 'upcoming',
      aiGenerated: false,
      partnerPriority: 88,
      weatherRelevance: 'any',
      timeOfDay: 'evening',
      vibeMatch: ['professional', 'ambitious', 'networker'],
      distanceLimit: 5000,
      viewCount: 102,
      joinRequestCount: 41,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];
}
